# Generated by Django 5.0.2 on 2024-07-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('_id', models.AutoField(db_column='sid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='SubjectEntry',
            fields=[
                ('_id', models.AutoField(db_column='tid', primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], max_length=2)),
                ('LAB', models.CharField(choices=[('L1', 'CCF L1'), ('L2', 'CCF L2'), ('L3', 'CCF L3'), ('L4', 'CCF L4'), ('L5', 'CCF L5'), ('L6', 'CCF L6'), ('L7', 'CCF L7'), ('L8', 'CCF L8'), ('L9', 'CCF L9'), ('MP LAB', 'MICRO PROCESSOR LAB'), ('PG LAB', 'PG LAB')], max_length=50)),
                ('allotted_hours', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'subjectentry',
                'unique_together': {('day', 'LAB', 'allotted_hours')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('_id', models.AutoField(db_column='tid', primary_key=True, serialize=False)),
                ('staff', models.ForeignKey(db_column='staffid', on_delete=django.db.models.deletion.CASCADE, to='fisat.staff')),
                ('subject', models.ForeignKey(db_column='subjectid', on_delete=django.db.models.deletion.CASCADE, to='fisat.subjectentry')),
            ],
            options={
                'db_table': 'timetableentry',
                'unique_together': {('staff', 'subject')},
            },
        ),
    ]
