# Generated by Django 5.0.6 on 2025-06-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectentry',
            old_name='_id',
            new_name='id',
        ),
    ]
