# Generated by Django 5.0.2 on 2024-07-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectentry',
            name='LAB',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
