# Generated by Django 5.0.2 on 2024-07-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0001_initial'),
    ]

    operations = [
    ]
