# Generated by Django 5.0.6 on 2025-06-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0002_rename__id_subjectentry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='timetableentry',
            old_name='_id',
            new_name='id',
        ),
    ]
