# Generated by Django 5.2.8 on 2025-11-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0003_rename__id_staff_id_rename__id_timetableentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectentry',
            name='period',
            field=models.CharField(default='2025-dec', max_length=20),
        ),
    ]
