# Generated by Django 5.2.8 on 2025-11-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0004_alter_subjectentry_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectentry',
            name='period',
            field=models.CharField(default='2025-Jul', max_length=20),
        ),
    ]
