# Generated by Django 5.2.8 on 2025-12-02 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0005_alter_subjectentry_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectentry',
            name='period',
            field=models.CharField(default='2025-dec', max_length=20),
        ),
        migrations.CreateModel(
            name='SubjectFacultyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_names', models.TextField()),
                ('period', models.CharField(max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisat.subjectentry')),
            ],
        ),
    ]
