# Generated by Django 5.2.14 on 2026-05-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0006_alter_subjectentry_period_subjectfacultymap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('layout_type', models.CharField(choices=[('classic', 'Classic (8 Hours)'), ('new', 'New (6 Hours / Friday 7 Hours)')], default='classic', max_length=20)),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(default='2025-dec', max_length=20)),
            ],
            options={
                'db_table': 'batch',
                'unique_together': {('name', 'period')},
            },
        ),
        migrations.CreateModel(
            name='BatchSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='fisat.batch')),
            ],
            options={
                'db_table': 'batchsubject',
            },
        ),
    ]
