# Generated by Django 6.0.5 on 2026-05-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0007_batch_batchsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'semester',
            },
        ),
    ]
