# Generated by Django 6.0.5 on 2026-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0008_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='period',
            field=models.CharField(default='2025-dec', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'period')},
        ),
    ]
