# Generated by Django 5.2.14 on 2026-05-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0009_batch_period_alter_batch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='layout_type',
            field=models.CharField(choices=[('classic', 'Classic (8 Hours)'), ('new', 'New (6 Hours / Friday 7 Hours)')], default='classic', max_length=20),
        ),
    ]
