# Generated by Django 5.0.6 on 2026-06-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0010_semester_layout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsubject',
            name='hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjectentry',
            name='is_auto_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LabPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(choices=[('L1', 'CCF L1'), ('L2', 'CCF L2'), ('L3', 'CCF L3'), ('L4', 'CCF L4'), ('L5', 'CCF L5'), ('L6', 'CCF L6'), ('L7', 'CCF L7'), ('L8', 'CCF L8'), ('L9', 'CCF L9'), ('MP LAB', 'MICRO PROCESSOR LAB'), ('PG LAB', 'PG LAB')], max_length=50)),
                ('allowed_days', models.CharField(default='M,T,W,Th,F', help_text='Comma-separated list of allowed days, e.g., M,T,W', max_length=50)),
                ('allowed_hours', models.CharField(default='1,2,3', help_text='Comma-separated list of allowed starting hour blocks, e.g., 1,2,3 or 4,5,6', max_length=100)),
                ('day_gap', models.IntegerField(default=1, help_text='Gap in days required between lab sessions for the same batch')),
                ('period', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'labpreference',
                'unique_together': {('lab_name', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ParallelSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_1', models.CharField(max_length=100)),
                ('subject_2', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisat.batch')),
            ],
            options={
                'db_table': 'parallelsubjectgroup',
            },
        ),
    ]
